[phases.setup]
aptPkgs = ["git", "unzip", "zip", "libzip-dev", "libpng-dev", "libjpeg-dev", "libfreetype6-dev"]

cmds = [
  "install-php-extensions gd zip"
]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader --no-interaction"]

[phases.build]
cmds = [
  "php bin/console cache:clear --env=prod --no-warmup",
  "php bin/console cache:warmup --env=prod"
]



