[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.intl", "php82Extensions.mbstring", "php82Extensions.xml", "composer"]

[phases.build]
cmds = [
  "composer install --no-dev --optimize-autoloader",
  "php bin/console cache:clear --env=prod",
  "php bin/console cache:warmup --env=prod"
]

[phases.deploy]
cmds = [
  "php bin/console doctrine:migrations:migrate --no-interaction --env=prod"
]

[start]
cmd = "frankenphp run --config /etc/caddy/Caddyfile"
